# Generated by Django 6.1 on 2026-08-31 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_created_at_user_reset_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
