# Generated by Django 6.1 on 2026-08-31 13:19

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_product_buy_price_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(default=authentication.models.generate_patient_id, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=authentication.models.generate_product_id, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(default=authentication.models.generate_sale_id, max_length=36, primary_key=True, serialize=False),
        ),
    ]
