# Generated by Django 6.1 on 2026-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_patient_id_alter_product_id_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
