# Generated by Django 6.1 on 2026-09-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_sale_product_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
    ]
