# Generated by Django 6.1 on 2026-09-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_expense_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_otp_created_at',
        ),
    ]
